import type { ArtStyle } from '@/types/story';

export const artStyles: ArtStyle[] = [
  {
    id: 'watercolor',
    name: { en: 'Watercolor', de: 'Aquarell', fr: 'Aquarelle' },
    emoji: '🎨',
    image: '/images/water color style.jpg',
    description: {
      en: 'Soft watercolor painting with flowing colors',
      de: 'Sanfte Aquarellmalerei mit fliessenden Farben',
      fr: 'Peinture aquarelle douce aux couleurs fluides',
    },
    prompt: 'Traditional watercolor painting, textured paper, delicate color washes (wet-on-wet technique), soft edges, visible artistic brushstrokes, transparent and flowing colors',
  },
  {
    id: 'concept',
    name: { en: 'Concept Art', de: 'Konzeptkunst', fr: 'Art conceptuel' },
    emoji: '✨',
    image: '/images/concept art style.jpg',
    description: {
      en: 'Professional digital concept art',
      de: 'Professionelle digitale Konzeptkunst',
      fr: 'Art conceptuel numérique professionnel',
    },
    prompt: 'Highly detailed digital concept art, dramatic lighting, epic composition, smooth rendering, focus on mood and atmosphere, wide-angle lens, matte painting aesthetic',
  },
  {
    id: 'anime',
    name: { en: 'Anime', de: 'Anime', fr: 'Anime' },
    emoji: '⭐',
    image: '/images/anime style.jpg',
    description: {
      en: 'Japanese anime style with expressive features',
      de: 'Japanischer Anime-Stil mit ausdrucksstarken Features',
      fr: 'Style anime japonais aux traits expressifs',
    },
    prompt: 'Modern digital anime art, high detail, expressive large eyes, dynamic composition, detailed cel-shading, vibrant palette, style of Makoto Shinkai',
  },
  {
    id: 'pixar',
    name: { en: 'Pixar 3D', de: 'Pixar 3D', fr: 'Pixar 3D' },
    emoji: '🎬',
    image: '/images/pixar art style 2.jpg',
    description: {
      en: 'Vibrant, warm Disney/Pixar style 3D animation',
      de: 'Lebendige, warme Disney/Pixar 3D-Animation',
      fr: 'Animation 3D Disney/Pixar vibrante et chaleureuse',
    },
    prompt: '3D render, Pixar cinematic style, natural eye proportion, subtle expression, highly detailed textures, octane render, volumetric lighting, vibrant colors, smooth shading, family-friendly',
  },
  {
    id: 'cartoon',
    name: { en: 'Cartoon', de: 'Cartoon', fr: 'Dessin animé' },
    emoji: '🎨',
    image: '/images/cartoon style.jpg',
    description: {
      en: 'Classic 2D cartoon style with bold colors',
      de: 'Klassischer 2D-Cartoon-Stil mit kräftigen Farben',
      fr: 'Style cartoon 2D classique aux couleurs vives',
    },
    prompt: '2D cartoon style, bold black outlines, vibrant flat colors (minimal shading/cel-shading), smooth vector quality, classic Saturday morning animation aesthetic',
  },
  {
    id: 'comic',
    name: { en: 'Comic Book', de: 'Comic', fr: 'Bande dessinée' },
    emoji: '💥',
    image: '/images/comic book style.jpg',
    description: {
      en: 'Comic book style with bold lines and halftone',
      de: 'Comic-Stil mit kräftigen Linien und Raster',
      fr: 'Style bande dessinée avec lignes épaisses et trames',
    },
    prompt: 'Classic American comic book art, heavy black ink lines, dynamic composition, visible halftone/Ben-Day dots, vibrant CMYK colors, style of Jack Kirby/Jim Lee',
  },
  {
    id: 'oil',
    name: { en: 'Oil Painting', de: 'Ölgemälde', fr: 'Peinture à l\'huile' },
    emoji: '🖼️',
    image: '/images/oil painting style.jpg',
    description: {
      en: 'Classic oil painting with rich textures',
      de: 'Klassisches Ölgemälde mit reichen Texturen',
      fr: 'Peinture à l\'huile classique aux textures riches',
    },
    prompt: 'Classic oil painting style, visible impasto brushstrokes, rich texture, heavy pigment, chiaroscuro lighting, canvas texture, museum quality art',
  },
  {
    id: 'steampunk',
    name: { en: 'Steampunk', de: 'Steampunk', fr: 'Steampunk' },
    emoji: '⚙️',
    image: '/images/steampunk style.jpg',
    description: {
      en: 'Victorian-era inspired with gears and brass',
      de: 'Von der viktorianischen Ära inspiriert mit Zahnrädern und Messing',
      fr: "Inspiré de l'ère victorienne avec engrenages et laiton",
    },
    prompt: 'Steampunk graphic novel illustration in the style of Sean Murphy. Victorian aesthetic with abundant brass and copper gears, cogs, and clockwork mechanisms. Visible leather grain, stitching on clothing, and metal patina on gears. Warm brown and muted amber color palette with restrained saturation. Clean linework with even shading and smooth gradients. Realistic human faces with natural proportions, detailed eyes, and subtle expressions.',
  },
  {
    id: 'cyber',
    name: { en: 'Cyberpunk', de: 'Cyberpunk', fr: 'Cyberpunk' },
    emoji: '🌃',
    image: '/images/cyber punk style.jpg',
    description: {
      en: 'Dark futuristic cyberpunk aesthetic',
      de: 'Dunkle futuristische Cyberpunk-Ästhetik',
      fr: 'Esthétique cyberpunk futuriste sombre',
    },
    prompt: 'Cyberpunk aesthetic, neon reflections, rainy streets, chrome, dense complexity, high contrast, dark atmosphere, volumetric fog, graphic novel illustration',
  },
  {
    id: 'chibi',
    name: { en: 'Chibi', de: 'Chibi', fr: 'Chibi' },
    emoji: '🌸',
    image: '/images/chibi style.jpg',
    description: {
      en: 'Cute chibi style with big heads and small bodies',
      de: 'Niedlicher Chibi-Stil mit grossen Köpfen und kleinen Körpern',
      fr: 'Style chibi mignon avec grandes têtes et petits corps',
    },
    prompt: 'Chibi style, super deformed (SD) proportions, massive head, tiny body, kawaii aesthetic, adorable, smooth illustration, minimalist detail',
  },
  {
    id: 'manga',
    name: { en: 'Manga', de: 'Manga', fr: 'Manga' },
    emoji: '📚',
    image: '/images/manga style.jpg',
    description: {
      en: 'Japanese manga style, black and white with screentones',
      de: 'Japanischer Manga-Stil, schwarz-weiss mit Rastern',
      fr: 'Style manga japonais, noir et blanc avec trames',
    },
    prompt: 'Traditional manga style, Japanese comic art, intricate detailed linework, black and white/monochrome, atmospheric screentones, dramatic lighting and composition',
  },
  {
    id: 'pixel',
    name: { en: 'Pixel Art', de: 'Pixelkunst', fr: 'Pixel art' },
    emoji: '👾',
    image: '/images/pixel style.jpg',
    description: {
      en: 'Retro 16-bit pixel art style',
      de: 'Retro 16-Bit Pixelkunst-Stil',
      fr: 'Style pixel art rétro 16 bits',
    },
    prompt: '16-bit pixel art style, low resolution, limited color palette, detailed sprite work, retro video game aesthetic, style of Final Fantasy VI',
  },
  {
    id: 'lowpoly',
    name: { en: 'Low Poly', de: 'Low Poly', fr: 'Low Poly' },
    emoji: '🔷',
    image: '/images/low poly 3-D style.jpg',
    description: {
      en: 'Minimalist geometric 3D style',
      de: 'Minimalistischer geometrischer 3D-Stil',
      fr: 'Style 3D géométrique minimaliste',
    },
    prompt: 'Low poly 3D model, isometric perspective, minimalist geometric shapes, vibrant solid colors, clear edges, retro video game aesthetic, style of Monument Valley',
  },
  {
    id: 'realistic',
    name: { en: 'Realistic', de: 'Realistisch', fr: 'Réaliste' },
    emoji: '📷',
    image: '/images/Real person.jpg',
    description: {
      en: 'Photorealistic illustration with natural lighting',
      de: 'Fotorealistische Illustration mit natürlichem Licht',
      fr: 'Illustration photoréaliste avec éclairage naturel',
    },
    prompt: 'Photorealistic children\'s book illustration, natural lighting, cinematic composition, real-world textures, shallow depth of field, professional photography aesthetic',
  },
];
