-- Test Lab (admin prompt-regression tooling)
--
-- 1. story_images.is_test / experiment_id: sandbox image versions generated by
--    Test Lab experiments. Excluded from every user-facing read (version lists,
--    active-image resolution, rehydration); version_index is still allocated
--    from the shared MAX+1 allocator so promote = flip the flag, no re-index.
-- 2. benchmark_scenes: curated reference pages (any story) used as the fixed
--    comparison set for prompt A/B runs. snapshot holds the scene context as it
--    was when added (prose, textPosition, characters) so the benchmark stays
--    interpretable even if the source story is later edited.
-- 3. testlab_experiments: one row per stage-rerun/A-B run; results holds the
--    per-target outcome (version pointers for image stages, verdict JSON for
--    eval stages).

ALTER TABLE story_images ADD COLUMN IF NOT EXISTS is_test BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE story_images ADD COLUMN IF NOT EXISTS experiment_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_story_images_is_test ON story_images(story_id) WHERE is_test;

CREATE TABLE IF NOT EXISTS benchmark_scenes (
  id SERIAL PRIMARY KEY,
  story_id VARCHAR(255) NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  page_number INTEGER NOT NULL,
  label TEXT,
  tags JSONB NOT NULL DEFAULT '{}'::jsonb,
  snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (story_id, page_number)
);

CREATE TABLE IF NOT EXISTS testlab_experiments (
  id SERIAL PRIMARY KEY,
  stage VARCHAR(50) NOT NULL,
  label TEXT,
  prompt_override TEXT,
  params JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  targets JSONB NOT NULL DEFAULT '[]'::jsonb,
  results JSONB NOT NULL DEFAULT '[]'::jsonb,
  error TEXT,
  created_by VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_testlab_experiments_created ON testlab_experiments(created_at DESC);
