import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'node:module';

const require_ = createRequire(import.meta.url);

// BEHAVIOUR PINNED: the empty-scene QC prompt moved from a string literal in
// validateEmptyScene into prompts/empty-scene-qc.txt on 2026-09-15, so the plate
// generator/critic pair could become a sibling-registry set over two file paths.
// EXPECTED below was rendered by the PRE-EXTRACTION code for these exact
// fixtures; the move is safe exactly as long as the built prompt still matches
// it byte for byte. Wording is unchanged — this was a move, not an edit.
//
// The geometry checks are still generated by GEOMETRY_DIMENSIONS
// (sceneGeometry.js), the one source the plate PROMPT also reads: they arrive
// through the declared {GEOMETRY_CHECK} placeholder, never as a frozen copy.

const FIXTURES: any[] = [
  {
    sceneDescription: 'A cobbled quay beside the harbour at dusk.',
    storyEra: '1930s',
    characterPlacements: [{ name: 'Lea', position: 'left foreground', depth: 'near' }, { name: 'Tomas', position: 'right midground' }],
    mainScenePrompt: 'The quay runs diagonally from the lower-left foreground to the upper-right background. Late afternoon light comes from the left. The harbour mouth opens as a bright gap at the far right.',
  },
  {
    sceneDescription: 'An empty forest clearing.',
    storyEra: null,
    characterPlacements: null,
    mainScenePrompt: '',
  },
];

const EXPECTED: string[] = ["This is a background scene for a children's book illustration. Small background figures, animals, and distant people are fine — they add life to the scene.\nEXPECTED SCENE: \"A cobbled quay beside the harbour at dusk.\"\n\nSTORY ERA: 1930s — render accordingly. Landmark reference photos are present-day; any modern elements visible in the photo must NOT appear in the output.\n\nCHARACTER PLACEMENTS TO BE COMPOSITED LATER:\n- Lea at left foreground (depth: near)\n- Tomas at right midground\n\nMAIN SCENE PROSE (what will be composited onto this empty scene):\n\"The quay runs diagonally from the lower-left foreground to the upper-right background. Late afternoon light comes from the left. The harbour mouth opens as a bright gap at the far right.\"\n\nCheck:\n- Setting / location: does it roughly match the expected scene? (FAIL if completely wrong location — e.g. expected a forest but got a city)\n- Naturalness: does the image look like a natural, plausible illustration of the scene? Or are there strange artefacts, geometry that doesn't make sense, doubled props, melted shapes, surfaces that change material mid-stroke, perspective lines that contradict each other, or anything that looks \"off\" for a competent painter? (FAIL — describe what looks unnatural)\n- Geometric artefact patches: are there large artificial-looking patches — white or near-white **rectangles, triangles, diagonals, wedges, or any solid geometric shape**, monochrome panels, blank patches, or obvious AI glitches that cover a meaningful portion of the frame? Pay special attention to bright triangular or diagonal cutouts that don't belong to the scene's geometry. (FAIL — name the shape and where it is)\n- Foreground space: is there visible open space in the foreground where main characters could be placed later? (FAIL if the entire foreground is filled with objects or walls)\n- Unrequested text or signage: does the image contain readable text, letters, numbers, shop signs, banners, posters, logos, labels, or written inscriptions that are NOT named in the expected scene? (FAIL — name where the text appears. A pub sign, street sign, poster text, or any inscription not explicitly requested counts. Distant painted banners with no readable text are OK.)\n- Anachronistic elements for the stated STORY ERA above: are there objects that don't fit the period? (FAIL — name them. Cars, parked vehicles, modern street lights, traffic signs, billboards, power lines, utility poles, satellite dishes, air conditioners, modern shopfront windows with price stickers, commercial ads, plastic bins, painted crosswalks, road markings, telephone poles, fire hydrants. Skip this check only if the story era is \"present-day\" or \"modern\".)\n4. Given the character placements above, does the empty scene have open, flat, usable ground at EACH of those frame positions? FAIL if a character position (e.g. \"far-left background\") maps to a frame region that is blocked by a wall, a building facade, a large prop, or the very edge of a receding corridor. Name the blocked position in the issue.\n5. Composition geometry — does this empty scene support the main scene's geometry? The plate's author was given these same three facts, so a disagreement is a real defect. Check:\n   a. Path / perspective direction — does any path, river, road, corridor, shoreline, horizon or major perspective line run in the direction the main scene prose describes (e.g. \"stretches to the right background\", \"diagonal from lower-left to upper-right\")?\n   b. Vanishing point / opening position — is it at the frame position the main scene implies (e.g. main scene says \"sliver of light at far right background\" → the opening sits at the upper-right, not centred or on the left)?\n   c. Lighting direction — does the light come from the direction the main scene names, consistent with its time of day and declared light source, with every shadow falling the same way?\n   FAIL with a specific fix instruction if any of them disagree. The issue description must name WHAT geometry is wrong AND the corrected direction/position. Example: \"path runs front-to-center instead of diagonally to the upper-right; regenerate with the path angled toward the upper-right corner\".\n\nReply JSON only: {\"pass\": true/false, \"issues\": [\"short issue\"], \"feedback\": \"one sentence naming WHAT to remove or fix — e.g. 'remove the pub sign at upper-left and the parked car at lower-right'. Be specific enough that a regeneration prompt can target the named elements.\"}", "This is a background scene for a children's book illustration. Small background figures, animals, and distant people are fine — they add life to the scene.\nEXPECTED SCENE: \"An empty forest clearing.\"\n\nCheck:\n- Setting / location: does it roughly match the expected scene? (FAIL if completely wrong location — e.g. expected a forest but got a city)\n- Naturalness: does the image look like a natural, plausible illustration of the scene? Or are there strange artefacts, geometry that doesn't make sense, doubled props, melted shapes, surfaces that change material mid-stroke, perspective lines that contradict each other, or anything that looks \"off\" for a competent painter? (FAIL — describe what looks unnatural)\n- Geometric artefact patches: are there large artificial-looking patches — white or near-white **rectangles, triangles, diagonals, wedges, or any solid geometric shape**, monochrome panels, blank patches, or obvious AI glitches that cover a meaningful portion of the frame? Pay special attention to bright triangular or diagonal cutouts that don't belong to the scene's geometry. (FAIL — name the shape and where it is)\n- Foreground space: is there visible open space in the foreground where main characters could be placed later? (FAIL if the entire foreground is filled with objects or walls)\n- Unrequested text or signage: does the image contain readable text, letters, numbers, shop signs, banners, posters, logos, labels, or written inscriptions that are NOT named in the expected scene? (FAIL — name where the text appears. A pub sign, street sign, poster text, or any inscription not explicitly requested counts. Distant painted banners with no readable text are OK.)\n\nReply JSON only: {\"pass\": true/false, \"issues\": [\"short issue\"], \"feedback\": \"one sentence naming WHAT to remove or fix — e.g. 'remove the pub sign at upper-left and the parked car at lower-right'. Be specific enough that a regeneration prompt can target the named elements.\"}"];

let build: any;

beforeAll(async () => {
  await require_('../../server/services/prompts.js').loadPromptTemplates();
  build = require_('../../server/lib/evalPipeline.js').buildEmptySceneQcPrompt;
});

describe('empty-scene QC prompt — extraction is a move, not an edit', () => {
  it('renders byte-identical to the pre-extraction literal (era + placements + geometry)', () => {
    expect(build(FIXTURES[0])).toBe(EXPECTED[0]);
  });

  it('renders byte-identical with no era, no placements and no main-scene prose', () => {
    expect(build(FIXTURES[1])).toBe(EXPECTED[1]);
  });

  it('leaves no unfilled placeholder in either built prompt', () => {
    for (const f of FIXTURES) expect(build(f).match(/\{[A-Z][A-Z0-9_]*\}/g)).toBe(null);
  });

  it('the geometry checks still come from the shared GEOMETRY_DIMENSIONS source', () => {
    const { buildGeometryJudgeChecks } = require_('../../server/lib/sceneGeometry.js');
    const generated = buildGeometryJudgeChecks(5);
    expect(generated.length).toBeGreaterThan(0);
    expect(build(FIXTURES[0])).toContain(generated);
  });
});
