import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'node:module';

const require_ = createRequire(import.meta.url);

// BEHAVIOUR PINNED: the empty-scene QC prompt moved from a string literal in
// validateEmptyScene into prompts/empty-scene-qc.txt on 2026-09-15, so the plate
// generator/critic pair could become a sibling-registry set over two file paths.
// EXPECTED below was rendered by the PRE-EXTRACTION code for these exact
// fixtures; the move is safe exactly as long as the built prompt still matches
// it byte for byte. Wording is unchanged — this was a move, not an edit. (The text
// check was re-worded on purpose on 2026-09-23: correctly spelled signage is allowed. The same
// day the figure rule was aligned with the plate generator and a medium and a camera check
// were added — see docs/decisions.md "The plate is judged on what its author was told". Later that day the era lines were aligned with the generator's
// "keep the landmark itself unchanged; only remove the modern surroundings" — see docs/decisions.md
// "A real landmark's plate is judged against its photo". On 2026-09-26 the figures check
// was re-worded to fail ANY person on a plate — see docs/decisions.md "A plate holds no people".)
//
// The geometry checks are still generated by GEOMETRY_DIMENSIONS
// (sceneGeometry.js), the one source the plate PROMPT also reads: they arrive
// through the declared {GEOMETRY_CHECK} placeholder, never as a frozen copy.

const FIXTURES: any[] = [
  {
    sceneDescription: 'A cobbled quay beside the harbour at dusk.',
    storyEra: '1930s',
    characterPlacements: [{ name: 'Lea', position: 'left foreground', depth: 'near' }, { name: 'Tomas', position: 'right midground' }],
    mainScenePrompt: 'The quay runs diagonally from the lower-left foreground to the upper-right background. Late afternoon light comes from the left. The harbour mouth opens as a bright gap at the far right.',
  },
  {
    sceneDescription: 'An empty forest clearing.',
    storyEra: null,
    characterPlacements: null,
    mainScenePrompt: '',
  },
];

const EXPECTED: string[] = ["This is a background plate for a children's book illustration: the place a page's characters are painted into later.\nEXPECTED SCENE: \"A cobbled quay beside the harbour at dusk.\"\n\nSTORY ERA: 1930s — render accordingly. Landmark reference photos are present-day; modern things around the landmark in the photo must NOT appear in the output — the landmark itself stays as the photo shows it.\n\nCHARACTER PLACEMENTS TO BE COMPOSITED LATER:\n- Lea at left foreground (depth: near)\n- Tomas at right midground\n\nMAIN SCENE PROSE (what will be composited onto this empty scene):\n\"The quay runs diagonally from the lower-left foreground to the upper-right background. Late afternoon light comes from the left. The harbour mouth opens as a bright gap at the far right.\"\n\nCheck:\n- Setting / location: does it roughly match the expected scene? (FAIL if completely wrong location — e.g. expected a forest but got a city)\n- Naturalness: does the image look like a natural, plausible illustration of the scene? Or are there strange artefacts, geometry that doesn't make sense, doubled props, melted shapes, surfaces that change material mid-stroke, perspective lines that contradict each other, or anything that looks \"off\" for a competent painter? (FAIL — describe what looks unnatural)\n- Geometric artefact patches: are there large artificial-looking patches — white or near-white **rectangles, triangles, diagonals, wedges, or any solid geometric shape**, monochrome panels, blank patches, or obvious AI glitches that cover a meaningful portion of the frame? Pay special attention to bright triangular or diagonal cutouts that don't belong to the scene's geometry. (FAIL — name the shape and where it is)\n- Frame edge: does the painted scene reach all four sides of the frame? (FAIL for a paper margin, mat, deckle or torn-paper edge, vignette, border, keyline or frame around the picture, or a smaller picture set inside the frame — name it and where it is.)\n- Figures: a plate holds no people. Is there any person, passer-by, crowd, rider, or silhouette of a person anywhere in the frame, however small or distant — even one the EXPECTED SCENE names — or an animal the EXPECTED SCENE does not name? (FAIL — name them and where they stand. A statue or carving that is part of the place is not a person.)\n- Foreground space: is there visible open space in the foreground where main characters could be placed later? (FAIL if the entire foreground is filled with objects or walls)\n- Wrong text: does the image contain a caption, title, label box or watermark laid over the picture, a misspelled word, or words on something that would not carry them (words across a wall, a tree or the sky)? (FAIL — name where the text appears. Correctly spelled writing an object of that kind carries in the real world — a shop name on its sign, a street name on a street sign — is OK, and so are distant painted banners with no readable text. A signature, monogram or initials anywhere in the picture FAILS.)\n- Anachronistic elements for the stated STORY ERA above: are there objects that don't fit the period? (FAIL — name them. Cars, parked vehicles, modern street lights, traffic signs, billboards, power lines, utility poles, satellite dishes, air conditioners, modern shopfront windows with price stickers, commercial ads, plastic bins, painted crosswalks, road markings, telephone poles, fire hydrants. A real landmark the scene is set at is never one of them — it stays as it really stands. Skip this check only if the story era is \"present-day\" or \"modern\".)\n4. Given the character placements above, does the empty scene have open, flat, usable ground at EACH of those frame positions? FAIL if a character position (e.g. \"far-left background\") maps to a frame region that is blocked by a wall, a building facade, a large prop, or the very edge of a receding corridor. Name the blocked position in the issue.\n5. Composition geometry — does this empty scene support the main scene's geometry? The plate's author was given these same facts, so a disagreement is a real defect. Check:\n   a. Path / perspective direction — does any path, river, road, corridor, shoreline, horizon or major perspective line run in the direction the main scene prose describes (e.g. \"stretches to the right background\", \"diagonal from lower-left to upper-right\")?\n   b. Vanishing point / opening position — is it at the frame position the main scene implies (e.g. main scene says \"sliver of light at far right background\" → the opening sits at the upper-right, not centred or on the left)?\n   c. Lighting direction — does the light come from the direction the main scene names, consistent with its time of day and declared light source, with every shadow falling the same way?\n   FAIL with a specific fix instruction if any of them disagree. The issue description must name WHAT geometry is wrong AND the corrected direction/position. Example: \"path runs front-to-center instead of diagonally to the upper-right; regenerate with the path angled toward the upper-right corner\".\n\nReply JSON only: {\"pass\": true/false, \"issues\": [{\"check\": \"<key>\", \"issue\": \"short issue\"}], \"feedback\": \"one sentence naming WHAT to remove or fix — e.g. 'remove the pub sign at upper-left and the parked car at lower-right'. Be specific enough that a regeneration prompt can target the named elements.\"} Each issue's \"check\" is the one key of the check it fails, from this list: setting (the setting or location), naturalness (unnatural shapes, doubled props, contradicting perspective), artefact (a white, black or monochrome box, panel or patch, or a border, frame, mat or margin around the picture), figures (any person, or an animal the scene does not name), foreground (no open foreground), text (any caption, label, lettering, signature or watermark), medium (a photograph, or a medium other than the art style), camera (the camera), light (the time of day or weather), era (an element from another era), placements (a character position with no usable ground), geometry (path direction, vanishing point or light direction), landmark (the landmark does not resemble its photo).","This is a background plate for a children's book illustration: the place a page's characters are painted into later.\nEXPECTED SCENE: \"An empty forest clearing.\"\n\nCheck:\n- Setting / location: does it roughly match the expected scene? (FAIL if completely wrong location — e.g. expected a forest but got a city)\n- Naturalness: does the image look like a natural, plausible illustration of the scene? Or are there strange artefacts, geometry that doesn't make sense, doubled props, melted shapes, surfaces that change material mid-stroke, perspective lines that contradict each other, or anything that looks \"off\" for a competent painter? (FAIL — describe what looks unnatural)\n- Geometric artefact patches: are there large artificial-looking patches — white or near-white **rectangles, triangles, diagonals, wedges, or any solid geometric shape**, monochrome panels, blank patches, or obvious AI glitches that cover a meaningful portion of the frame? Pay special attention to bright triangular or diagonal cutouts that don't belong to the scene's geometry. (FAIL — name the shape and where it is)\n- Frame edge: does the painted scene reach all four sides of the frame? (FAIL for a paper margin, mat, deckle or torn-paper edge, vignette, border, keyline or frame around the picture, or a smaller picture set inside the frame — name it and where it is.)\n- Figures: a plate holds no people. Is there any person, passer-by, crowd, rider, or silhouette of a person anywhere in the frame, however small or distant — even one the EXPECTED SCENE names — or an animal the EXPECTED SCENE does not name? (FAIL — name them and where they stand. A statue or carving that is part of the place is not a person.)\n- Foreground space: is there visible open space in the foreground where main characters could be placed later? (FAIL if the entire foreground is filled with objects or walls)\n- Wrong text: does the image contain a caption, title, label box or watermark laid over the picture, a misspelled word, or words on something that would not carry them (words across a wall, a tree or the sky)? (FAIL — name where the text appears. Correctly spelled writing an object of that kind carries in the real world — a shop name on its sign, a street name on a street sign — is OK, and so are distant painted banners with no readable text. A signature, monogram or initials anywhere in the picture FAILS.)\n\nReply JSON only: {\"pass\": true/false, \"issues\": [{\"check\": \"<key>\", \"issue\": \"short issue\"}], \"feedback\": \"one sentence naming WHAT to remove or fix — e.g. 'remove the pub sign at upper-left and the parked car at lower-right'. Be specific enough that a regeneration prompt can target the named elements.\"} Each issue's \"check\" is the one key of the check it fails, from this list: setting (the setting or location), naturalness (unnatural shapes, doubled props, contradicting perspective), artefact (a white, black or monochrome box, panel or patch, or a border, frame, mat or margin around the picture), figures (any person, or an animal the scene does not name), foreground (no open foreground), text (any caption, label, lettering, signature or watermark), medium (a photograph, or a medium other than the art style), camera (the camera), light (the time of day or weather), era (an element from another era), placements (a character position with no usable ground), geometry (path direction, vanishing point or light direction), landmark (the landmark does not resemble its photo)."];

let build: any;

beforeAll(async () => {
  await require_('../../server/services/prompts.js').loadPromptTemplates();
  build = require_('../../server/lib/evalPipeline.js').buildEmptySceneQcPrompt;
});

describe('empty-scene QC prompt — extraction is a move, not an edit', () => {
  it('renders byte-identical to the pre-extraction literal (era + placements + geometry)', () => {
    expect(build(FIXTURES[0])).toBe(EXPECTED[0]);
  });

  it('renders byte-identical with no era, no placements and no main-scene prose', () => {
    expect(build(FIXTURES[1])).toBe(EXPECTED[1]);
  });

  it('leaves no unfilled placeholder in either built prompt', () => {
    for (const f of FIXTURES) expect(build(f).match(/\{[A-Z][A-Z0-9_]*\}/g)).toBe(null);
  });

  it('the geometry checks still come from the shared GEOMETRY_DIMENSIONS source', () => {
    const { buildGeometryJudgeChecks } = require_('../../server/lib/sceneGeometry.js');
    const generated = buildGeometryJudgeChecks(5, ['path', 'opening', 'lighting']);
    expect(generated.length).toBeGreaterThan(0);
    expect(build(FIXTURES[0])).toContain(generated);
  });
});

// The plate is judged on what its author was told (2026-09-23): the plate
// prompt opens with ART STYLE and carries a SHOT line, so the judge gets both.
describe('empty-scene QC — medium, camera and figures', () => {
  const STYLE = 'A loose watercolour painting with visible brushwork.';
  it('asks the medium and the camera when the plate was given them', () => {
    const p = build({ ...FIXTURES[1], artStyle: STYLE, shot: 'aerial' });
    expect(p).toContain(STYLE);
    expect(p).toMatch(/photograph/);
    expect(p).toContain('framed as the aerial shot');
    expect(build({ ...FIXTURES[1], shot: 'eye-level' })).toContain('framed at eye level');
    expect(p.match(/\{[A-Z][A-Z0-9_]*\}/g)).toBe(null);
  });
  it('asks neither when the plate was given neither', () => {
    const p = build(FIXTURES[1]);
    expect(p).not.toContain('Medium:');
    expect(p).not.toContain('Camera:');
  });
  it('never excuses a person on a plate, and fails an animal the scene does not name', () => {
    expect(build(FIXTURES[1])).not.toMatch(/figures, animals, and distant people are fine/);
    expect(build(FIXTURES[1])).toMatch(/a plate holds no people/);
    expect(build(FIXTURES[1])).toMatch(/an animal the EXPECTED SCENE does not name/);
  });
});
